### ISSUE TITLE
XSS vulnerability in clipboard.swf

### ISSUE THREAD

**Issue by masatokinugawa** [Viper007Bond/syntaxhighlighter#12]
Please go to the following URL and click the flash object. You can reproduce.
http://www.viper007bond.com/wordpress/wp-content/plugins/syntaxhighlighter/syntaxhighlighter2/scripts/clipboard.swf?highlighterId=\%22%29%29}catch%28e%29{};alert%281%29//

**Comment by Viper007Bond** [comment]
That link doesn't work for me but you're correct about the XSS issue -- it was previously privately reported to me (please do that next time for security issues) and I've been working on a solution.

**Comment by Viper007Bond** [comment]
As a temporary fix, the file has been blanked out and a new version released: 7b1c5a73f8b2ecea244fb49c62cc06eb7d5c8b87
