### ISSUE TITLE
HTML belonging to the post are shown as highlighted code

### ISSUE THREAD

**Issue by Caroga** [Viper007Bond/syntaxhighlighter#13]
Hi,

I've installed your plugin from the wordpress plugin factory as well as by cloning it from Git. 
Using several shortcodes gives me all the same problem: <br/> tags are shown in the highlight. Also, html encoded characters are shown as the encoded entity. 

I've attached an image for you to see.
I have not modified any content of your plugin. Do you have any idea what I could check or how to fix this issue? 
Many thanks in advance.

![image](https://f.cloud.github.com/assets/4005934/464030/80c3a7f6-b5ba-11e2-99e1-f88fd52a75b4.png)
Extra info:
WordPress 3.5.1.
SyntaxHighlighter Evolved Version 3.1.6

**Comment by Viper007Bond** [comment]
For the future, please post support requests here: http://wordpress.org/support/plugin/syntaxhighlighter  Thanks.

To answer your question though, another plugin is likely doing that if I had to guess. My plugin replaces it's shortcodes with `<pre>` tags before the WordPress code that adds `<br />`s runs and that code doesn't insert them inside of `<pre>` tags.

**Comment by Caroga** [comment]
Thank you for your quick response.
I will address any further issues on the plugins support section, sorry for this inconvenience.

I have no further plugins which affects my content, but I do have a custom theme. Switched back to the TwentyTwelve theme and the problem did not occur anymore. 

I will debug the theme's parsing.

Thank you for your advice.
