### ISSUE TITLE
Line numbers are shifted

### ISSUE THREAD

**Issue by MartinThoma** [Viper007Bond/syntaxhighlighter#18]
When you look at [this page](http://martin-thoma.com/inverting-matrices/) for example, you can see that line 21 is not in the same line as the line it numbers.

**Comment by Viper007Bond** [comment]
Looks fine here in Firefox, Chrome, and IE10.

**Comment by MartinThoma** [comment]
Are you sure? I think it is quite easy to miss it, so I've marked the wrong section: http://imgur.com/IXxWJLL
(Google Chrome 27.0.1453.110 on Ubuntu)

I thought the reason might be that I'm logged in (so I have the black bar at the top), but it looks the same when I'm in Chromes incognito mode (logged out).

Looks fine on Firefox 21.0 on Ubuntu...

**Comment by Viper007Bond** [comment]
Here's what I see (Windows 7): http://imgur.com/a/KDXFr

Looks like maybe a font issue or something?

**Comment by MartinThoma** [comment]
You're right, we (our browsers) definitely use different fonts. When you look at "u" you can see it quite clear.
I've also created a .gif which shows it: http://i.imgur.com/fnt0Zcv.gif

When I uncheck "font-family: "Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace !important" from shCore.css?ver=3.0.83c with developer tools I get better results.

I've just seen that [Consolas](http://en.wikipedia.org/wiki/Consolas) is a font from Microsoft Windows Vista. I guess I can't display that on my Ubuntu Linux machine, s

**Comment by MartinThoma** [comment]
After installing Bitsream Vera fonts with

sudo apt-get install ttf-bitstream-vera

everything looks fine :-)

**Comment by Viper007Bond** [comment]
Yeah, it tries to use Consolas (Windows only), then the next one, then the next one, etc. I guess some of the last result fonts don't work quite right. That font list is from the upstream project though: https://github.com/alexgorbatchev/SyntaxHighlighter

**Comment by MartinThoma** [comment]
Thanks for your help!

I found the bug here: https://github.com/alexgorbatchev/SyntaxHighlighter/issues/77
