### ISSUE TITLE
 "data[c]" in c code showed as "data1"

### ISSUE THREAD

**Issue by hpt** [Viper007Bond/syntaxhighlighter#26]
Hello,

When trying to highlight c language code with syntaxhighlighter, the "data[c]" is showed as "data1". Something like this:

[code lang="c"]

char data[100];
int cpp;

for (c=0;c<100;c++)
data[c]="a";
[/code]

will be showed as this:

![c](https://f.cloud.github.com/assets/120404/1331945/cb223eb6-356c-11e3-9f4b-b5f74aa94009.jpg)

**Comment by Viper007Bond** [comment]
Hmm, works fine for me: http://alexpublictest.wordpress.com/2013/10/22/syntaxhighlighter-evolved-issue-26-test/

**Comment by hpt** [comment]
Could you help me on this? It's strange. Why I always get "1" for "[c]" or "[cpp]" or "[php]" in the source code highlighting here?

**Comment by Viper007Bond** [comment]
Can you provide a URL to where this is happening for you? It's hard to debug without seeing it for myself.

**Comment by hpt** [comment]
Please see https://96.126.98.8/blog/?p=1837

**Comment by Viper007Bond** [comment]
Check out the HTML source code of the page -- the "data1" there as well so the issue is NOT with the highlighting package. 

The problem is either with my plugin or another plugin you have enabled. I recommend you start by disabling all other plugins that you have active (except mine) to see if that resolves the issue.

You can also check the database to see what the `post_content` value is for the post. Is "data1" there too?

**Comment by hpt** [comment]
Thanks. I have disabled all other plugins besides yours, but the problem wasn't fixed. And I also checked the post_content value, it looks like this, it's "data[c]" there:

[c]
int data[100];
int c

for (c=0;c&lt;=100;c++)
    data[c]=c;

for (c=0;c&lt;=100;c++)
    printf(&quot;%d\n&quot;,data[c]);
[/c]

**Comment by hpt** [comment]
The "<" and '"' in pervious comment are both converted to html's "&" format in the post_content.

**Comment by Viper007Bond** [comment]
I just realized what's going on. You're using the shortcode `[c]` to wrap your code and yet you have `[c]` in your code itself which is confusing WordPress's shortcode parser.

Try doing this instead:

`[code lang="c"] your code here [/code]`

**Comment by hpt** [comment]
I have tested surrounding my code with [code lang="c"] and [/code]. But [c] is still showed as 1. In the mean time, I have disabled other plugins.
