### ISSUE TITLE
'autolinks' preference ignored for bash

### ISSUE THREAD

**Issue by ntwb** [Viper007Bond/syntaxhighlighter#27]
Take a look at http://make.wordpress.org/core/handbook/automated-testing/#installation

Code being used is in the WordPress blog post:

```
[sourcecode language="bash" autolinks="false"]
$ svn co http://develop.svn.wordpress.org/trunk/ wordpress-develop
$ cd wordpress-develop
[/sourcecode]
```

Resulting Code Display Output:

``` bash
$ svn co <a href="http://develop.svn.wordpress.org/trunk/" rel="nofollow">http://develop.svn.wordpress.org/trunk/</a> wordpress-develop
$ cd wordpress-develop
```

Expected Code Display Output

``` bash
$ svn co http://develop.svn.wordpress.org/trunk/ wordpress-develop
$ cd wordpress-develop
```

**Comment by Viper007Bond** [comment]
`autolinks` controls the highlighter and basically toggles making URLs clickable in the final render. It's entirely client-side.

This looks like `make_clickable()` at work but I can't reproduce this though. My plugin should parse its shortcodes before `make_clickable()` runs, which should ignore the insides of the `<pre>` tags that my plugin leaves behind.

I copy/pasted the whole source code from the handbook into my 3.7 test install and it worked as expected.

Perhaps this is exposing a bug in some code custom to WP.org. Hmm...

**Comment by ntwb** [comment]
Thanks Alex,
I created a ticket http://meta.trac.wordpress.org/ticket/217 and will follow up there.

**Comment by ntwb** [comment]
And there is a WordPress ticket with patch ready to go :)
http://core.trac.wordpress.org/ticket/23756

**Comment by Viper007Bond** [comment]
Weird, I don't have that patch applied and yet it still works fine for me...

**Comment by ntwb** [comment]
Indeed weird, maybe that patch and/or unit tests need a closer look...
