### ISSUE TITLE
A brush for GraphViz

### ISSUE THREAD

**Issue by skarred** [Viper007Bond/syntaxhighlighter#9]
## A Brush for the Dot Language in GraphViz

The brush can be found on this gist: [shBrushDot.js](https://gist.github.com/skarred/4997425). Please feel free to use it, modify it, or add it to the plugin as you see fit

I created this brush some time ago. You can see it in action on [my blog](http://karalli.net/archives/adding-graphviz/).

**Comment by Viper007Bond** [comment]
Thanks but I'm not looking to support every known language under the sun. Instead I've made it easy for people to extend my plugin and add support for their favorite niche languages.

Details here: http://www.viper007bond.com/wordpress-plugins/syntaxhighlighter/adding-a-new-brush-language/

**Comment by skarred** [comment]
No problem, I was able to add it myself a while back.  I just wanted to offer it...
